security
Aleksandr-K88org/Task.3.1.3 pull request #1
Opened 2024-02-14 16:48 UTC by Aleksandr-K88

2024-02-15 19:42 UTC, pdasilem requested changes

2024-02-15 19:42 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controller/AdminController.java
> +        Optional<User> userByName = userService.findByName(user.getName());
бизнес логику - в сервис

2024-02-15 19:42 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controller/AdminController.java
> +        Optional<User> userByName = userService.findByName(user.getName());
в сервис

2024-02-15 19:42 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controller/UserController.java
> +        String name = principal.getName();
зачем так сложно?
у тебя не юзер не сможет сюда дойти

2024-02-15 19:42 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
избавиться от игер

2024-02-15 19:42 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/service/UserServiceImpl.java
> +        return new HashSet<>(userRepository.findAll());
зачем в сет?

2024-02-15 19:42 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/service/UserServiceImpl.java
> +        String updatePassword = updateUser.getPassword();
почему я сомневаюсь, что с паролями у тебя будет здесь порядок?

2024-02-28 15:10 UTC, Aleksandr-K88 commented on src/main/java/ru/itmentor/spring/boot_security/demo/service/UserServiceImpl.java
> +        String updatePassword = updateUser.getPassword();
Проверил, работает. Если упростить у меня при изменении юзера пароль повторно шифруется.

2024-02-28 15:12 UTC, pdasilem approved these changes

2024-02-29 18:02 UTC, merged