REST
Aleksandr-K88org/Task.3.1.3 pull request #2
Opened 2024-03-08 00:17 UTC by Aleksandr-K88

2024-03-08 00:18 UTC, Aleksandr-K88 commented
REST

2024-03-09 07:01 UTC, pdasilem requested changes
а где рест контроллер на юзера?

2024-03-09 07:01 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/configs/WebSecurityConfig.java
> +                .antMatchers("/user**").hasAnyRole("ADMIN", "USER")
а здесь?

2024-03-13 15:40 UTC, Aleksandr-K88 reviewed
Да, забыл про юзера. Добавил

2024-03-13 15:42 UTC, Aleksandr-K88 commented on src/main/java/ru/itmentor/spring/boot_security/demo/configs/WebSecurityConfig.java
> +                .antMatchers("/user**").hasAnyRole("ADMIN", "USER")
Добавил

2024-03-14 13:13 UTC, pdasilem approved these changes

2024-03-20 14:34 UTC, merged